name: Update Stock Data

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # UTC 時間 01:00-07:00 等於台灣時間 09:00-15:00
    - cron: '0,15,30,45 1-7 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yfinance requests pandas
          
      - name: Run script
        run: python weiyu_stock.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # 檢查 data.js 是否有改變
          git add data.js
          
          # 如果 git diff 檢查發現沒有變動，直接跳過 commit 並結束
          if git diff --quiet && git diff --staged --quiet; then
            echo "沒有資料變動，跳過更新。"
          else
            git commit -m "自動更新: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
